name = "MeshesRecipes"
uuid = "edf05e14-c34c-4d80-8520-1a1ec72e5d6d"
authors = ["zerefwayne <aayushjog@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"

[compat]
AbstractPlotting = "0.15"
Makie = "0.11"
Meshes = "0.5, 0.7"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
